### ISSUE TITLE
Error displayed - "There was an error performing the requested operation. Please try again or contact us for assistance."

### ISSUE THREAD

**Issue by nhienkrajak** [trydirect/orocrm#4]
Deployment is OK with default compose and config files. Message consumer is running. Can start the Application on browser, and successfully login as Admin.

The application seems working fine with the demo data. However, there is always a notification displayed - "There was an error performing the requested operation. Please try again or contact us for assistance."

Is there any additional configuration should be done to get rid of it?

**Comment by vsilent** [comment]
Hi @nhienkrajak , we have updated orocrm configs and docs, issue must be fixed now. 
You can retry the deployment. Best regards.

**Comment by nhienkrajak** [comment]
Thank you very much for your support. It took me days wrestling with this issue without any progress.

Now I'm trying your new docker-compose and config files. Just expose different ports "8180:80" and "41443:443".

There is an error saying network property "name" is not valid (actually Docker doc describes this property is only available in compose file version 3.7.) But it is gone after I upgrade docker-compose from 1.17 to 1.26.1.

There is likely a typo in this command:

`docker-compose exec orocrm bash -c "cd orocrm && php bin/console oro:install
`

I believe it should be instead: 

`docker-compose exec orocrm bash -c "cd backend && php bin/console oro:install
`

Anyway, I can get the application installed successfully.
But when accessing it in Chrome, after login, the screen seems forever staying in "Loading..."

I clear the cache, restart orocrm, restart docker container..., but it doesn't help.
There is a [old post](https://forum.oroinc.com/orocrm/orocrm-installationtechnical-issues-or-problems/topic/stuck-on-loading...-after-login/) in OroCRM forum mentions to this issue:

However, in my system (Ubuntu 18.04), node/nodejs is avaible. So still keep trying to figure out what the problem is.

**Comment by vsilent** [comment]
Thank you for your contribution @nhienkrajak , README has been updated. 
> "But when accessing it in Chrome, after login, the screen seems forever staying in "Loading..."

We can not reproduce the problem from above. 
It makes sense to check browser's console logs for errors and possibly container logs too.  

Regards

**Comment by nhienkrajak** [comment]
Thank you for your comment. I checked the browser's console and figured out that the css were not generated.
Then I tried manually regenerate them with the command:

```
php bin/console oro:assets:build
```

However, it stopped with an error 

```
/var/www/backend/vendor/oro/platform/build/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

Error: Can't resolve 'orosync/js/extend/autobahn' in ''
....
.....
In OroAssetsBuildCommand.php line 270:

Build failed.
...
```

It is likely an issue related with permission, so I tried the commands:

```
chmod -R 777 /var/www/backend
chown -R www-data:www-data /var/www/backend
```

And, voila, now the assets can be installed and re-built successfully.

Finally, the application runs properly without any error. I will check it and report if there is any other issue.

Thanks again for your project & support.
Best  Regards
